language: node_js

services:
  - docker

node_js:
  - 12

before_install:
  - docker build -t react-dev -f Dockerfile.dev .
  - docker run -d -p 3000:3000 react-dev
  - docker build -t react-prod -f Dockerfile .
  - docker run -d -p 80:80 react-dev
  - docker ps -a

install:
  - yarn install

script:
  - yarn test